Gitlab ci 2
Otus-DevOps-2018-09/Serega2780_microservices pull request #6
Opened 2019-01-05 08:09 UTC by Serega2780

# Выполнено ДЗ №17

 - [x] Основное ДЗ
 - [x] Задание со *

## В процессе сделано:
 - Pipeline из предыдущего ДЗ расширен путем добавления задач stage и production;
 - Рассмотрена работа pipeline в режиме с тэгами;
 - Рассмотрена работа pipeline в режиме с динамическим окружением.

 - Выполнено первое задание со *. Для этого исходный image ruby:2.4.2 дополнен пакетами gcloud, docker-ce, docker-machine. Соответствующий Dockerfile в папке ./gitlab-ci. Полученный образ называется ruby-docker:2.4.2, именно он используется в .gitlab-ci.yml. При пуше новой ветки с помощью конструкции if then else + средствами gcloud проверяется наличие виртуальной машины в GCE с соответствующим именем. Если она есть об этом выводится соответствующее сообщение, если нет - она создается docker-machine. Выбран именно docker-machine, а не gcloud, так как полученная ВМ уже будет иметь установленный docker. Добавлен новый job branch stop GCE Server с режимом manual. При нажатии на соответствующую кнопку в UI запускается механизм удаления ВМ gcloud.

 - Выполнено второе задание со **. На шаге build из исходников в папке ./docker-monolith собирается образ приложения reddit, который затем пушится на docker hub. На шаге branch review из этого образа средствами gcloud на созданной в GCE ВМ запускается контейнер приложения reddit.

## Как запустить проект:
 - скачать образ 270580/docker-ruby:2.4.2 с docker hub; 
 - в файле .gitlab-ci.yml необходимо заменить имеющиеся учетные данные для docker hub на свои; также в соответствующую папку на сервере gitlab-ci нужно скопировать свой GCE Credentials файл с правами на создание ВМ. Указать правильное имя этого файла в .gitlab-ci.yml;
 - сделать push данной ветки  в свой репозитарий gitlab; убедиться, что pipeline отработал; при этом в GCE должна появиться новая ВМ с запущенным контейнером приложения reddit.

## Как проверить работоспособность:
 - Например, перейти по ссылке http://<NEW_GCE_VM_WHITE_IP>:9292

## PR checklist
 - [x] Выставил label с номером домашнего задания
 - [x] Выставил label с темой домашнего задания

2019-01-05 16:46 UTC, ujhgj requested changes
Добрый день, Сергей! 
Работа понравилась, при этом есть замечание по сборке образа ruby-docker. Прокомментируйте его пожалуйста

2019-01-05 16:46 UTC, ujhgj commented on gitlab-ci/Dockerfile
> +COPY docker-ce_18.06.1_ce_3-0_debian_amd64.deb /docker-ce_18.06.1_ce_3-0_debian_amd64.deb
Откуда берётся этот файл?

2019-01-05 20:10 UTC, Serega2780 commented on gitlab-ci/Dockerfile
> +COPY docker-ce_18.06.1_ce_3-0_debian_amd64.deb /docker-ce_18.06.1_ce_3-0_debian_amd64.deb
С offsite. Я решил, что в данном случае будет удобнее ставить docker-ce из пакета, вместо того, чтобы писать то множество команд для добавления репозитария и установки сопутствующих пакетов.

2019-01-05 21:47 UTC, ujhgj commented on gitlab-ci/Dockerfile
> +COPY docker-ce_18.06.1_ce_3-0_debian_amd64.deb /docker-ce_18.06.1_ce_3-0_debian_amd64.deb
Александр )
Смотрите, допустим мы сейчас передадим ссылку на ваш репозиторий третьему человеку. Если он попытается собрать этот образ у себя, он получит ошибку, так как у него нет этого файла. Ему тоже придётся объяснить, что это за файл и откуда его скачать. Много действий, не правда ли? Лучше заскриптовать всё это внутри докерфайла. Кстати, на сайте докера в документации есть ссылка на т.н. convenience script, который знает как развернуть докер на любом линуксовом дистрибутиве. Делается это примерно так: 
`curl https://get.docker.com/ | bash` и это можно вставить в инструкцию RUN докерфайла.
Рекомендую использовать этот подход и отказаться от COPY и вручную скачанного локального deb-пакета.

2019-01-06 01:10 UTC, Serega2780 commented on gitlab-ci/Dockerfile
> +COPY docker-ce_18.06.1_ce_3-0_debian_amd64.deb /docker-ce_18.06.1_ce_3-0_debian_amd64.deb
Большое спасибо, Александр, за рекомендацию. 
Действительно, с этим скриптом образ собрался, как говорится, без сучка, без задоринки. При установке из пакета (казалось бы родного), он у меня постоянно ругался на неустановленные зависимости: iptables,init-system-helpers. Даже пришлось их в --ignore-depends заносить. А со скриптом все завелось с первого раза. Что называется: рекомендация  из разряда best practicies) По-больше бы таких.

2019-01-06 09:37 UTC, ujhgj approved these changes

2019-01-06 09:38 UTC, merged